name: preflight-checkers 
on:
  pull_request_target:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
 contents: read
 security-events: write

jobs:
  checker:
    uses: qualcomm/qcom-actions/.github/workflows/multi-checker.yml@main
    with:
        repolinter: true # default: true
        semgrep: true # default: true
        copyright-license-detector: true # default: true
        pr-check-emails: true # default: true

    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}